export const SET_MOVIES = 'SET_MOVIES';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT'
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR'
export const SET_PREVIEW_MOVIE = 'SET_PREVIEW_MOVIE'
export const PREVIEW_MOVIE_ERROR = 'PREVIEW_MOVIE_ERROR'
export const SET_SEARCHING_MOVIES = 'SET_SEARCHING_MOVIES'